### ISSUE TITLE
Add missing commands (if any)

### ISSUE THREAD

**Issue by pboothe** [m-lab/nodeinfo#2]
Right now the current set of commands is pretty small. It's fine for now, but more is likely better. Our partner org which runs ops should be consulted on this.

**Comment by pboothe** [comment]
Consulting now. :)

**Comment by nkinkade** [comment]
* I would suggest using `ip address show` [instead of  `ifconfig -a`](https://github.com/m-lab/nodeinfo/blob/master/main.go#L51). 50% of the `ifconfig` output is interface statistics, which we don't need or want here. Sadly, the version of `ip` on our CoreOS nodes doesn't support JSON output, but the version on my local machine (4.18.0) does. I wonder if it's worth figuring out how to get a more feature complete version of `ip` onto the nodes so we can use the `-json` flag to get machine readable output for the win!!

* Similar to above, I would suggest `ip -{4,6} route show` over `route -A <family>`. Again, if we can get a more feature-complete version of `ip` on the platform nodes, this output can also be in JSON.

* I might also suggest capturing the output of `cat /etc/os-release`. This could provide us valuable information about OS version details. For example, maybe we notice some change in metrics on a machine but can't explain them. Looking back at the output of this data might allow us to say: "Oh, CoreOS was upgraded from version X to version Y on that date!".

* I would also suggest capturing the content of these files. `bios_version` is self-explanatory. `chassis_serial` is the Dell Service Tag.
    * /sys/class/dmi/id/bios_version
    * /sys/class/dmi/id/chassis_serial

That's all I can think of for now.
